version: "2"
services:
  db:
    hostname: db
    image: mongo
    restart: always
    expose:
    - "27017"
    ports:
    - 27017:27017
  core:
    environment:
      - ADMIN_EMAIL=
      - ADMIN_PW=
      - SECRET=QWERTYUIOPASDFGHJKLZXCVBNM
      - DB_HOST=db
    restart: on-failure
    depends_on:
      - db
    build: ./backend
    links:
    - db
    ports:
    - 8080:3000